fileVersion: 1
id: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
name: APPLICATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: LEVER_RAW
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: cc66d3da-176a-4f8d-9a98-bd5b64ffd49a
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ID
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 8d68cddc-6205-4622-9de0-7252b7e6d30a
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARIANT
        defaultValue: ""
        description: ""
        name: LINKS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7c2fd025-bae2-41ca-8eb5-f40762899fd8
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: BOOLEAN
        defaultValue: ""
        description: ""
        name: _FIVETRAN_DELETED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: fb2f5fe1-02fd-4fd1-8361-3f6a0c815310
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ARCHIVED_REASON_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d4695be6-16d2-4299-9e21-f15327974a96
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: OPPORTUNITY_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 037e66cf-c220-4c0e-b2aa-305be29411c5
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: POSTING_HIRING_MANAGER_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1e9a2a91-02e9-46d7-9890-e273478ff3db
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: POSTING_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1c6e84c7-baef-4584-ac47-42959e137e3b
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: POSTING_OWNER_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 989cbc67-1a04-441e-9d2d-c55685a648c9
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: REFERRER_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d72ff553-dfe2-45b1-b4d6-606fe8eff600
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: TIMESTAMP_TZ(9)
        defaultValue: ""
        description: ""
        name: _FIVETRAN_SYNCED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 502a17c0-2b07-456b-afc2-17ac3078f646
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(16384)
        defaultValue: ""
        description: ""
        name: COMMENTS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c30f3250-dd6a-4b97-887c-b3527f8aeafe
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: TYPE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c345eb3e-e3f3-4232-bb4b-07ac07d22682
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: COMPANY
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 264c50dd-71f5-4ddf-9455-4ce2a6d04253
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ARCHIVED_AT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: fb7cec82-5bbc-4276-abe4-636be3f06459
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: CREATED_AT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b57d363e-a076-43d1-ad88-97f8f872d902
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: REQUISITION_FOR_HIRE_MANAGER
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: bffc25d8-d31d-4811-96f1-43ad71b16944
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: REQUISITION_FOR_HIRE_CODE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 43f3bdab-37a2-42fe-9002-a2387a1b3683
          stepCounter: e9a4bca1-a87a-4a87-a06e-d97e62f8c9b4
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: REQUISITION_FOR_HIRE_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: APPLICATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
