config:
  entities:
    nodeTypes:
      "455":
        defaultStorageLocation: null
        isDisabled: false
  packageVariables: |-
    {#------------------------------------------------------------------------------------------------------#}
    {#-- The following variable can be customized to include or remove column name patterns that  needs to be masked --#}
    {#-- It is used in the macro found below.                                                     --#}

    {% set maskList =
          ['PHONE',
          'ADDRESS',
          'NAME',
          'ACCOUNT','EMAIL','INCOME']
    %}
fileVersion: 1
id: "@coalesce/snowflake/data-security-package"
name: data-security
packageID: "@coalesce/snowflake/data-security-package"
releaseID: 33995e47-f476-4610-8f46-beba450b13fc
type: Package
